// Tier 1 of the agent bench: what each agent actually says about itself.
//
// No model, no credential, no network beyond spawning something already
// installed — so it is repeatable and can run in CI. What it produces is the
// capability matrix in docs/AGENTS.md, regenerated rather than hand-maintained,
// because "opencode reports mcpCapabilities.http" is a fact about a version and
// not a thing that stays true.
//
// Tier 2 — a real turn, a permission request, a memory write through the rail —
// needs somebody logged in and is deliberately not here (#111).
import { spawn } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const bin = (name) => resolve(here, "../node_modules/.bin", name);

/// Only agents this repository pins. An agent fetched at run time is #120's
/// subject, and a matrix built from one is a matrix about whatever was
/// published this morning.
const AGENTS = [
  { name: "claude", command: bin("claude-agent-acp"), args: [] },
];

const frame = (id, method, params) =>
  JSON.stringify({ jsonrpc: "2.0", id, method, params }) + "\n";

/// The client's own handshake, byte for byte — see desktop/src-tauri/src/acp.rs.
const INITIALIZE = frame(1, "initialize", {
  protocolVersion: 1,
  clientCapabilities: { fs: { readTextFile: false, writeTextFile: false } },
});

/// The rail as the client sends it: headers are a list, not an object. Sent as
/// an object the agent reaches the rail unauthenticated and answers from
/// nothing, which reads as the product not working (#68).
const NEW_SESSION = frame(2, "session/new", {
  cwd: process.cwd(),
  mcpServers: [ {
    name: "workroom", type: "http", url: "http://127.0.0.1:1/api/rail/bench",
    headers: [ { name: "Authorization", value: "Bearer bench" } ],
  } ],
});

function ask(agent, seconds = 60) {
  return new Promise((done) => {
    const child = spawn(agent.command, agent.args, { stdio: ["pipe", "pipe", "pipe"] });
    const said = { agent: agent.name, stderr: "" };
    let buf = "";

    const finish = () => { child.kill("SIGKILL"); done(said); };
    const timer = setTimeout(() => { said.error ??= `no answer in ${seconds}s`; finish(); }, seconds * 1000);

    child.on("error", (e) => { said.error = e.message; clearTimeout(timer); done(said); });
    child.stderr.on("data", (d) => { said.stderr += d; });
    child.stdout.on("data", (d) => {
      buf += d;
      let i;
      while ((i = buf.indexOf("\n")) >= 0) {
        const line = buf.slice(0, i).trim();
        buf = buf.slice(i + 1);
        if (!line) continue;
        let msg;
        try { msg = JSON.parse(line); } catch { continue; }

        if (msg.id === 1) {
          said.initialize = msg.result ?? { error: msg.error };
          child.stdin.write(NEW_SESSION);
        }
        if (msg.id === 2) {
          said.session = msg.result ? "opened" : `refused: ${msg.error?.message ?? "?"}`;
          clearTimeout(timer);
          finish();
        }
      }
    });

    setTimeout(() => child.stdin.write(INITIALIZE), 1500);
  });
}

const yes = (v) => (v === true || (v && typeof v === "object") ? "yes" : "—");

function row(said) {
  const r = said.initialize ?? {};
  const caps = r.agentCapabilities ?? {};
  const session = caps.sessionCapabilities ?? {};
  const mcp = caps.mcpCapabilities ?? r.mcpCapabilities ?? {};
  const auth = (r.authMethods ?? []).map((m) => m.id).join(", ") || "—";

  return [
    `\`${r.agentInfo?.name ?? said.agent}\``,
    r.agentInfo?.version ?? "—",
    r.protocolVersion ?? "—",
    yes(mcp.http),
    yes(caps.loadSession),
    yes(session.close),
    Object.keys(session).sort().join(", ") || "—",
    auth,
    said.session ?? said.error ?? "—",
  ];
}

const HEAD = [ "agent", "version", "protocol", "mcp http", "loadSession",
               "close", "sessionCapabilities", "authMethods", "session/new" ];
const START = "<!-- capabilities: measured, not typed -->";
const END = "<!-- /capabilities -->";

const results = [];
for (const agent of AGENTS) results.push(await ask(agent));

const table = [
  `| ${HEAD.join(" | ")} |`,
  `|${HEAD.map(() => "---").join("|")}|`,
  ...results.map((r) => `| ${row(r).join(" | ")} |`),
].join("\n");

const block = `${START}\n\n${table}\n\nRegenerated by \`pnpm bench:capabilities\`. Anything typed here by hand is a\nclaim about a version that has already moved.\n\n${END}`;

const doc = resolve(here, "../../docs/AGENTS.md");
const text = await readFile(doc, "utf8");
if (text.includes(START)) {
  await writeFile(doc, text.replace(new RegExp(`${START}[\\s\\S]*?${END}`), block));
  console.log(`docs/AGENTS.md updated.\n\n${table}`);
} else {
  console.log(`${table}\n\nAdd this between ${START} and ${END} in docs/AGENTS.md.`);
}

for (const said of results) {
  if (said.error) { console.error(`${said.agent}: ${said.error}`); process.exitCode = 1; }
  if (said.stderr.trim()) console.error(`${said.agent} said on stderr: ${said.stderr.trim().slice(0, 300)}`);
}
